### ISSUE TITLE
Add Mailfence to the list of email services

### ISSUE THREAD

**Issue by resto1231** [devbret/online-opsec#3]
Hello,

I would like to make a contribution to this project. My name is Orestis i work for [Mailfence ](https://mailfence.com)a secure and private email provider. I would like to add mailfence to the list of email providers, would that be possible?

Please let me know if you need more info on my side.

Kind regards,

Orestis

**Comment by devbret** [comment]
Hello Orestis,

Thank you for your comment. I took a look at Mailfence, and I'd be happy to add them to the Online OpSec resource. Please check back in a couple of hours to see the update.

Cheers,

Bret
